GET http://localhost:8080/api/v1/jobs/opening
GET http://localhost:8080/api/v1/jobs/opening
POST http://localhost:8080/api/v1/jobs/opening
DELETE http://localhost:8080/api/v1/jobs/opening
PUT http://localhost:8080/api/v1/jobs/opening
